version: "3.3"

services:

  webserver:
    build: 
      context: ./appserver
    image: webserver
    container_name: webserver
    depends_on:
      - mypostgres
    ports:
      - "8080:8080" 
      - "80:8080"
    networks:
      - front-tier
      - back-tier
  mypostgres:
    build:
      context: ./database
    image: postgresdb
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ggal1701
    volumes:
      - type: volume
        source: psql_data
        target: /var/lib/postgresql/data 
    networks:
      - back-tier
volumes:
  psql_data:
networks:
  front-tier:
  back-tier:



  https://www.youtube.com/watch?v=P_W9mqN5ERw
  https://kamang-it.tistory.com/entry/DockerShellScriptTomcatMavenSpringJavaUbuntu-Spring-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B0%9C%EB%B0%9C-%ED%9B%84-%EB%B0%94%EB%A1%9C-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0